### PR TITLE
Code style fixes (PSR-12)

### PR DESCRIPTION
**Pull request by hordijk**
Introduce PHPCS to perform code style checks.

### CODE REVIEW

**Comment by hordijk** [comment]
@tdgroot  not all code style issues are fixed yet:

```
<?xml version="1.0" encoding="UTF-8"?>
<phpcs version="3.5.5">
<file name="ecurring-api-php\tests\eCurringHttpClientTest.php" errors="1" warnings="0" fixable="0">
    <error line="11" column="1" source="Squiz.Classes.ValidClassName.NotCamelCaps" severity="5" fixable="0">Class name &quot;eCurringHttpClientTest&quot; is not in PascalCase format</error>
</file>
<file name="ecurring-api-php\src\eCurringHttpClient.php" errors="1" warnings="0" fixable="0">
    <error line="24" column="1" source="Squiz.Classes.ValidClassName.NotCamelCaps" severity="5" fixable="0">Class name &quot;eCurringHttpClient&quot; is not in PascalCase format</error>
</file>
<file name="ecurring-api-php\src\Endpoint\AbstractCollectionEndpoint.php" errors="1" warnings="0" fixable="0">
    <error line="31" column="15" source="PSR1.Methods.CamelCapsMethodName.NotCamelCaps" severity="5" fixable="0">Method name &quot;AbstractCollectionEndpoint::rest_list&quot; is not in camel caps format</error>
</file>
<file name="ecurring-api-php\src\Endpoint\AbstractEndpoint.php" errors="4" warnings="0" fixable="0">
    <error line="49" column="15" source="PSR1.Methods.CamelCapsMethodName.NotCamelCaps" severity="5" fixable="0">Method name &quot;AbstractEndpoint::rest_create&quot; is not in camel caps format</error>
    <error line="66" column="15" source="PSR1.Methods.CamelCapsMethodName.NotCamelCaps" severity="5" fixable="0">Method name &quot;AbstractEndpoint::rest_read&quot; is not in camel caps format</error>
    <error line="82" column="15" source="PSR1.Methods.CamelCapsMethodName.NotCamelCaps" severity="5" fixable="0">Method name &quot;AbstractEndpoint::rest_update&quot; is not in camel caps format</error>
    <error line="99" column="15" source="PSR1.Methods.CamelCapsMethodName.NotCamelCaps" severity="5" fixable="0">Method name &quot;AbstractEndpoint::rest_delete&quot; is not in camel caps format</error>
</file>
</phpcs>
```

Do you want to rename rest_create to restCreate etc. However this will be a breaking change.
Or do you want to introduce ignore statements in the code to cope with this?
And what to do with eCurringHttpClientTest?

**Comment by hordijk** [comment]
Once all the issues are solved we can introduce 
```
phpcs:
    standard: PSR12
```
 in the grumphp.yml and add a github action like https://github.com/marketplace/actions/php_codesniffer-check-with-annotations

**Review by tdgroot — APPROVED** [review]
Looks good to me!

**Comment by tdgroot** [comment]
@hordijk thanks for proposing these code style changes. We internally use PSR-2 (and more recently PSR-12) as well, so I really welcome these changes.

As for the remaining cs issues, let's ignore `Squiz.Classes.ValidClassName.NotCamelCaps` and `PSR1.Methods.CamelCapsMethodName.NotCamelCaps` for now. As you probably know, this can be configured by supplying a [phpcs.xml](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file) file.

**Comment by hordijk** [comment]
I've added a phpcs.xml and only excluded the rules for the files we cannot fix without breaking changes. Added some comment in the phpcs.xml as well that refers to this PR to clarify slightly.

**Review by tdgroot — APPROVED** [review]

**Pull request merged**
