### PR TITLE
Add support for the transactions API

### PR DESCRIPTION
**Pull request by hordijk**
This address `Implement Transactions API` of the roadmap

### CODE REVIEW

**Comment by hordijk** [comment]
This PR depends on #6, since that PR contains the fix:
- rest_delete does not support 204 - No Content

I can update this PR once more if #6 is merged.

**Comment by hordijk** [comment]
The id's used by transactions are not integers but strings instead, hence the rest_delete and rest_read method signature had to change. Instead of changing we could duplicate the implementation in the TransactionEndpoint, like

```php
$result = $this->client->performHttpCall(
     'GET',
     sprintf('%s/%s', $this->getResourcePath(), $id) . $this->buildQueryString($filters)
);

return $this->resourceFactory->createFromApiResult($result->data, $this->getResourceObject());
```
let me know what you prefer so I can update the PR accordingly.

**Comment by tdgroot** [comment]
Could you please update your branch so it's up to date with last merged PR?

**Comment by hordijk** [comment]
The branch is updated with master.

**Comment by hordijk** [comment]
Do you know when a new release will be created containing all PR's? 

The roadmap section in the README.md needs to updated slightly before a release.

**Review by tdgroot — APPROVED** [review]

**Comment by tdgroot** [comment]
@hordijk all your changes have been released under version 0.4.0!

**Comment by hordijk** [comment]
Thanks!

**Pull request merged**
